### ISSUE TITLE
Save copy of RV questionnaires as CSV files

### ISSUE THREAD

**Issue by rafael5** [vistadataproject/VAM2ProjectManagement#42]
Save an extra copy of the RV questionnaire files (currently Excel) using 'save as'  CSV.

CSV files will display properly in the Github repository.

**Comment by davidfaulkner08** [comment]
@rafael5 Due to the VAM2 RiskVision instance being changed and/or updated, certain files (Including the questionnaire) are either missing or located somewhere else. I've contacted Bobbi to understand why the RV instance was changed and if or how I can obtain existing files. Additionally, the VA network (Primarily Email) is under-performing. Once I talk to Bobbi, I can complete this task.

**Comment by rafael5** [comment]
Not sure I understand what you mean by 'certain files'. Could you explain?

AFAIK the "RV questionnaire"  is just a web application, so there are no 'questionnaire files'. 
RV then generates the 20+ output files (spreadsheets) from that.

**Comment by davidfaulkner08** [comment]
"Certain files" was just a simplification in references to ATO processes that are no longer in the location that they were in initialy. The "Questionnaire" is in reference to the CIA or Security Categorization, which contains various files we need. This was primarily the document I needed, but is no longer where it was in RiskVision. I'm still waiting on Bobbi, but as previously mentioned, Outlook on the VA network has been underperforming, so I'm unsure if Bobbie has even yet received my email. Ultimately, I'm unsure as to why VAM's RiskVision instance was changed/updated and without prior warning, thus my concern that data/files might have been lost, but likely just misplaced. I hope that answers your questions.

**Comment by davidfaulkner08** [comment]
Correction. Upon looking back into RiskVision, sections are back to normal. So, the documents/processes are where they should be. This was likely due to RiskVision glitch or maintenance. The confusion mainly stemed from the fact that I noticed links going to different pages and processes (Like the PIA) being shown as incomplete. All these facts gave the impression of a recently changed RV instance. [wipes sweat off forehead
]
