### ISSUE TITLE
Project management tools on Github

### ISSUE THREAD

**Issue by rafael5** [vistadataproject/VAM2ProjectManagement#6]
## github-based project management tools

* https://github.com/marketplace
* https://zube.io/
* https://www.zenhub.com/
* https://www.quora.com/Which-project-management-tools-are-deeply-integrated-with-GitHub
* https://asana.com/
* https://github.com/marketplace/waffle
* https://github.com/marketplace/category/project-management
* https://github.com/features/project-management/

**Comment by mfuroyama** [comment]
On a related note, the *Zube*, *Zenhub* and *Waffle.io* have all been granted required, limited 3rd-party access to the `vistadataproject` organization and repos, so running trial demos against our repos shouldn't be a problem.

**Comment by rafael5** [comment]
Great. Thank you Mike.

Is there any significant, practical ( useful) difference between these
four? Or others we should look into?

**Comment by mfuroyama** [comment]
I demo'ed Zenhub and Waffle.io; they were both pretty similar, functionality-wise and price-wise. Both of those tools ticked the basic requirement check-boxes that I was looking for as a tech-lead:

- [x] Cross-repo issue tracking / project management
- [x] Epic management / Agile process tools
- [x] Release management
- [x] Reports

Either one of these tools, combined with the powerful functionality already built into the GitHub site would definitely work from a dev perspective.

If I was forced to choose though, I'd pick Zenhub...mostly because I think Zenhub's tight GitHub integration and the browser plugin which overlays functionality directly into the GitHub site was really convenient. Either way tho, we should be able to make it work.

**Comment by rafael5** [comment]
For project management, do you have any thoughts/guidance?  Mostly we are going to be tracking issues / tasks (which do not involve code; they involve tracking documents). ...

**Comment by mfuroyama** [comment]
Hmm, I wonder if you couldn't use a similar workflow (GitHub, Zenhub) for the Project Management parts of the project as well. What I mean is, if we're talking about managing mostly Markdown documents (with images), you could:
* Treat the PM documents as code artifacts, managing version via GitHub git repos
* Assign GitHub issues to each document to track progress, completion dates, milestones, etc.
* Use 3rd-party tools to produce reports based on the document completion issues
* Leverage CI tools and GitHub hooks to do things like automatic document versioning, conversion, packaging, etc.

IMHO, the only major thing missing from Zenhub (and I think Waffle.io) that would help from a PM standpoint is a built-in Gantt chart builder.

Again, my humble opinion, but I prefer the lighter touch of the GitHub + Markdown (+ ZenHub/Waffle.io) combo. I think that toolset is lightweight, flexible and good enough to support several workflows adequately. Heavier-weight tools like Jira, Rational, etc. might provide more specialized tools and reports, but I don't think it's worth the associated cruft.

**Comment by rafael5** [comment]
closing for now.... will re-visit later

**Comment by nilesh1402** [comment]
@JashLal  Please research and if required open new issues and assign it to your self as research.
